---
apiVersion: v2
appVersion: "2025-07-25"
description: A lightweight NodeJS server that emulates the iOS HomeKit API
name: homebridge
version: 0.0.2  # Placeholder, will be set by GitHub Actions
kubeVersion: ">=1.28.0-0"
keywords:
  - homebridge
  - homekit
home: https://github.com/snixon/helm-charts/tree/main/charts/apps/homebridge
icon: https://avatars0.githubusercontent.com/u/38217527?s=400&v=4?sanitize=true
sources:
  - https://homebridge.io/
  - https://github.com/homebridge/homebridge
  - https://github.com/homebridge/docker-homebridge
maintainers:
  - name: snixon
    email: snixon@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.2.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Upgraded homebridge-docker version to "2025.07.25"
      links:
        - name: Detailed release notes
          url: https://github.com/homebridge/docker-homebridge/releases/tag/2025-07-25
